내용의 구성은 "[인공지능을 위한 기초수학](http://matrix.skku.ac.kr/math4ai/Math4AI.pdf/)/[파이썬 데이터 분석](https://codingalzi.github.io/pydata/)/신나는 대학수학"을 참조한다. 

- 스칼라(scalar): 길이, 넓이, 질량, 온도 - 크기만 주어지만 완전히 표시되는 양
- 벡터(vector): 속도, 위치이동, 힘 - 크기뿐만 아니라 방향까지 지정하지 않으면 완전히 표 현할 수 없는 양
- 벡터는 크기와 방향을 갖는 유향선분 - 2차원, 3 차원 공간의 벡터는 화살표로 표현 가능

# 벡터

#### 정의. [ $n$ 차원 벡터 $(n$-dimensional vector)]

$n$ 개의 실수의 순서조 $\left(x_{1}, x_{2}, \ldots, x_{n}\right)$ 을 $n$ 차원 벡터 $(n$-dimensional vector)라 하고
$$
\mathbf{x}=\left(x_{1}, x_{2}, \ldots, x_{n}\right)=\left[\begin{array}{c}
x_{1} \\
x_{2} \\
\vdots \\
x_{n}
\end{array}\right]_{n \times 1}
$$
로 나타낸다. 이때 실수 $x_{1}, x_{2}, \ldots, x_{n}$ 을 $\mathrm{x}$ 의 성분이라 한다.


* 벡터의 상등 

$\mathbb{R}^{n}$ 의 벡터
$$
\mathbf{x}=\left[\begin{array}{c}
x_{1} \\
x_{2} \\
\vdots \\
x_{n}
\end{array}\right], \quad \mathbf{y}=\left[\begin{array}{c}
y_{1} \\
y_{2} \\
\vdots \\
y_{n}
\end{array}\right]
$$

에 대하여 $x_{i}=y_{i}(i=1,2, \ldots, n)$ 이면 $\mathrm{x}=\mathrm{y}$ 라고 한다.

##  벡터 덧셈과 뺄셈

- 차원이 같은 벡터 두 개의 덧셈은 같은 위치에 있는 항목끼기 더한 결과로 이루어진 벡터를 생성한다.

$$
\begin{align*}
(1, 2) + (2, 1) &= (1+2, 2+1)
= (3, 3) \\[1ex]
(6, 3, 2) + (1, 7, 9) & = (6+1, 3+7, 2+9)
= (7, 10, 11)
\end{align*}
$$

- 벡터 $a$와 벡터 $b$의 합 $a+b$의 의미를 아래 그래프에서처럼 해석할 수 있다.

![images/VectorAddition.png](images/VectorAddition.png)

출처: [위키백과](https://en.wikipedia.org/wiki/Euclidean_vector)


- 차원이 같은 벡터 두 개의 덧셈은 같은 위치에 있는 항목끼기 뺀 결과로 이루어진 벡터를 생성한다.

$$
\begin{align*}
(1, 2) - (2, 1) &= (1-2, 2-1) 
= (-1, 1) \\[1ex]
(6, 3, 2) - (1, 7, 9) & = (6-1, 3-7, 2-9) 
= (5, -4, -7)
\end{align*}
$$

- 벡터 $a$와 벡터 $b$의 합 $a-b$의 의미를 아래 그래프에서처럼 해석할 수 있다.

![images/vector_subtraction.png](images/vector_subtraction.png)


출처: [위키백과](https://en.wikipedia.org/wiki/Euclidean_vector)

In [169]:
#<img #src="https://raw.githubusercontent.com/codingalzi/pydata/master/notebooks/images/vector_subtraction.png" #width="20%">




<img src="https://raw.githubusercontent.com/codingalzi/pydata/master/notebooks/images/vector_subtraction.png" width="20%">

%%hide output

### 벡터 스칼라 곱셈

- 숫자 하나와 벡터의 곱셈을 스칼라 곱셈이라 부른다. 

- 스칼라 곱셈은 벡터의 각 항목을 지정된 숫자로 곱해 새로운 벡터를 생성한다. 

$$
\begin{align*}
3\cdot (1, 2) &= (3\cdot 1, 3\cdot 2) = (3, 6) \\[1ex]
2\cdot (6, 3, 2) & = (2\cdot 6, 2\cdot 3, 2\cdot 2) = (12, 6, 4)
\end{align*}
$$

- 스칼라 곱셈의 기하적 의미
![images/Scalar_mult_2.png](images/Scalar_mult_2.png)

<table>
<tr>
    <td><img src="https://raw.githubusercontent.com/codingalzi/pydata/master/notebooks/images/Scalar_mult_2.png" width="50%"></td>
     <td><img src="https://raw.githubusercontent.com/codingalzi/pydata/master/notebooks/images/Scalar_mult_2.png" width="50%"></td>
</tr>
</table>

출처: [위키백과](https://en.wikipedia.org/wiki/Euclidean_vector)

![images/Scalar_mult_3.png](images/Scalar_mult_3.png)

## 벡터 내적

- 차원이 같은 벡터 두 개의 내적은 같은 위치에 있는 항목끼기 곱한 후 모두 더한 값이다.  
벡터 $u = (u_1, \cdots, u_n)$와 벡터 $v = (v_1, \cdots, v_n)$가 주어졌을 때
두 벡터의 내적은 아래와 같다. 

$$
\begin{align*}
u \cdot v &= \sum_{i=1}^n u_i\cdot v_i \\
&= u_1\cdot v_1 + \cdots + u_n\cdot v_n
\end{align*}
$$

- 벡터 내적의 기하적 의미

두 개의 벡터 $A$와 $B$가 주어졌고, 벡터 $B$의 길이가 1이라고 가정하자.  
그러면 내적 $A \cdot B$는 벡터 $A$가 벡터 $B$ 방향으로 사영되었을 때의 길이를 나타낸다. 

![images/dot_product.png](images/dot_product.png)

<img src="https://raw.githubusercontent.com/codingalzi/pydata/master/notebooks/images/dot_product.png" width="20%">

출처: [위키백과](https://en.wikipedia.org/wiki/Dot_product)

- 임의의 벡터 $B$에 대한 내적 $A \cdot B$는 다음과 같다. ($\theta$ 두 벡터가 이루는 각을 나타낸다.)

$$
A \cdot B = \vert A\vert\cdot \vert B\vert \cdot \cos\theta
$$

- 벡터의 크기

벡터 $v = (v_1, \cdots, v_n)$가 주어졌을 때 각 항목별 제곱의 합은 $v$와 $v$ 자신의 내적과 같다.

$$v \cdot v = v_1^2 + \cdots + v_n^2$$

그런데 이 값은 정확하게 벡터 $v$의 크기 $\vert v\vert$의 제곱이다. 
따라서 다음이 성립한다. 

$$\vert v\vert = \sqrt{v \cdot v} = \sqrt{v_1^2 + \cdots + v_n^2}$$

예를 들어 벡터 $(3, 4)$의 크기는 다음과 같다.

$$\vert (3, 4)\vert  = \sqrt{3^2 + 4^2} = \sqrt{5^2} = 5$$

## $\blacktriangleright$ Numpy 사용  

1차원 어레이로 구현하자.

$$
\mathbf{x}=\left(1,2,3 \right)=\left[\begin{array}{c}
1 \\
2 \\
3
\end{array}\right]
$$


$$
\mathbf{y}=\left(4,5,6 \right)=\left[\begin{array}{c}
4 \\
5 \\
6
\end{array}\right]
$$

In [170]:
import numpy as np

In [171]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [172]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [173]:
x + y

array([5, 7, 9])

In [174]:
2*x

array([2, 4, 6])

In [175]:
np.dot(x,y)

32

#  행렬

행렬(matrix)은 보통 숫자들을 직사각형 형태로 배열한 것이다. 

$$
A= [a_{ij}]_{i=1,...,n, j=1,...,n}=\left[\begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1 n} \\
a_{21} & a_{22} & \cdots & a_{2 n} \\
\vdots & \vdots & & \vdots \\
a_{i 1} & a_{i 2} & \cdots & a_{i n} \\
\vdots & \vdots & & \vdots \\
a_{m 1} & a_{m 2} & \cdots & a_{m n}
\end{array}\right]
$$

예를 들어, $1, 2, 3, 4, 5, 6$ 여섯 개의 항목을 가진 
행렬의 모양(shape)은 네 종류가 있다.   
이유는 6을 두 개의 양의 정수의 곱셈으로 표현하는 방법이 네 가지이기 때문이다. 

$$ 6 = 1\times6 = 2\times 3 = 3 \times 2 = 6 \times 1$$

* $1\times 6$ 행렬: 한 개의 행과 여섯 개의 열

\begin{bmatrix}
    1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}

* $2 \times 3$ 행렬: 두 개의 행과 세 개의 열

\begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6
\end{bmatrix}

* $3 \times 2$ 행렬: 세 개의 행과 두 개의 열

\begin{bmatrix}
    1 & 2 \\
    3 & 4 \\
    5 & 6
\end{bmatrix}

* $6 \times 1$ 행렬: 여섯 개의 행과 한 개의 열

\begin{bmatrix}
    1 \\
    2 \\
    3 \\
    4 \\
    5 \\
    6
\end{bmatrix}

## 특수 행렬

- 영행렬

영행렬(zero matrix)이란 행렬의 모든 원소의 값이 0인 행렬을 말한다.
예를 들어 아래 행렬은 (3, 2) 모양의 영행렬이다.

$$
\begin{bmatrix}
    0 & 0 \\
    0 & 0 \\
    0 & 0
\end{bmatrix}
$$

- 단위행렬

단위행렬(identity matrix)은 정사각형 모양의 행렬 중에서 대각선 상에 위치한 항목은 1이고
나머지는 0인 행렬을 말한다. $I_n$은 $n\times n$ 행렬로 아래와 같다. 
$$
I_{n}=\left[\begin{array}{cccc}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{array}\right]
$$


예를 들어  

$$
I_{5}=\left[\begin{array}{cccc}
1 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0  \\
0 & 0 & 1 & 0 & 0  \\
0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1  
\end{array}\right]
$$

##  행렬 덧셈과 뺄셈

모양이 같은 두 행렬의 덧셈/뺄셈은 항목별로 더한/뺀 결과로 이루어진 행렬이다. 
즉, 벡터의 덧셈/뺄셈과 동일한 방식이다.
예를 들어, $2 \times 3$ 행렬의 덧셈/뺄셈은 다음과 같다.

$$
\begin{align*}
\begin{bmatrix}1&3&7\\1&0&0\end{bmatrix} 
+ \begin{bmatrix}0&0&5\\7&5&0\end{bmatrix}
&= \begin{bmatrix}1+0&3+0&7+5\\1+7&0+5&0+0\end{bmatrix} = \begin{bmatrix}1&3&12\\8&5&0\end{bmatrix}\\[2ex]
\begin{bmatrix}1&3&7\\1&0&0\end{bmatrix} 
- \begin{bmatrix}0&0&5\\7&5&0\end{bmatrix}
&= \begin{bmatrix}1-0&3-0&7-5\\1-7&0-5&0-0\end{bmatrix} = \begin{bmatrix}1&3&2\\-6&-5&0\end{bmatrix}
\end{align*}
$$

## 행렬의 스칼라 곱셈

숫자 하나와 행렬의 곱셈을 행렬 스칼라 곱셈이라 부른다. 
스칼라 곱셈은 행렬의 각 항목을 지정된 숫자로 곱해 새로운 행렬을 생성한다.
즉, 벡터의 스칼라 곱셈과 동일한 방식이다. 

예를 들어, (2, 3) 모양의 행렬의 스칼라 곱셈은 다음과 같다.

$$
\begin{align*}
2\cdot 
\begin{bmatrix}1&8&-3\\4&-2&5\end{bmatrix}
&= \begin{bmatrix}2\cdot 1&2\cdot 8&2\cdot -3\\2\cdot 4&2\cdot -2&2\cdot 5\end{bmatrix} = \begin{bmatrix}2&16&-6\\8&-4&10\end{bmatrix}
\end{align*}
$$

## 행렬 곱셈

$m \times n$ 행렬 $A$와 $n \times p$ 행렬 $B$의 곱은 $m \times p$ 행렬이며, 
각 $(i, j)$번째 항목은 다음과 같이 정의된다.

$$
\begin{align*}
(A B)_{ij}
&= \sum _{k=1}^{n} A_{ik} \cdot B_{kj} \\
&= A_{i1} \cdot B_{1j} + A_{i2} \cdot B_{2j} + \cdots + A_{in} \cdot B_{nj}
\end{align*}
$$

그림으로 나타내면 다음과 같다.

![images/Matrix_mult_diagram.png](images/Matrix_mult_diagram.png)
<img src="https://raw.githubusercontent.com/codingalzi/pydata/master/notebooks/images/Matrix_mult_diagram.png" width="30%">

출처: [위키백과](https://en.wikipedia.org/wiki/Dot_product)

즉, 좌측 행렬 열의 수 $n$과 우측 행렬 행의 수 $n$이 같은 경우에만 곱셈이 가능하다.


예를 들어, $2 \times 3$ 행렬과 $3 \times 2$ 행렬의 곱셈은 다음과 같다.

$$
\begin{align*}
\begin{bmatrix}
    1&0&2\\-1&3&1
\end{bmatrix}
\begin{bmatrix}
    3&1\\2&1\\1&0
\end{bmatrix}
&=
\begin{bmatrix}
    (1\cdot 3+0\cdot 2+2\cdot 1)&(1\cdot 1+0\cdot 1+2\cdot 0)\\(-1\cdot 3+3\cdot 2+1\cdot 1)&(-1\cdot 1+3\cdot 1+1\cdot 0)
\end{bmatrix} =  
\begin{bmatrix}
    5&1\\4&2
\end{bmatrix}
\end{align*}
$$

## 행렬 곱셈과 벡터내적

$m \times n$ 행렬 $A$와 $n \times p$ 행렬 $B$의 곱 $AB$의 $(i, j)$번째 항목 $(A B)_{ij}$를 살펴본다. 

- ### 행벡터와 열벡터

행렬 $A$의 $i$ 행벡터를 

$$A_i = (A_{i1},\dots, A_{in}),$$

행렬 $B$의 $j$ 열벡터를 

$$
B^j=\left[\begin{array}{cccc} 
B_{0j} \\
\vdots \\
B_{nj}
\end{array}\right]
$$

라 하자. 

- ### 행렬곱셈과 내적

이제 $AB$의 $(i, j)$번째 항목 $(A B)_{ij}$는  


$$
\begin{align*}
(A B)_{ij}
&= \sum _{k=1}^{n} A_{ik} \cdot B_{kj} \\
&= A_{i1} \cdot B_{1j} + A_{i2} \cdot B_{2j} + \cdots + A_{in} \cdot B_{nj}\\
&= A_i \cdot B^j
\end{align*}
$$

즉, $(A B)_{ij}$는 $A$의 $i$번째  행벡터와 $B$의 $j$번째 열벡터의 **내적**으로 정의된다.

반면에 행렬 $A$의 $i$ 행벡터를 

$$A_i = (A_{i0},\dots, A_{i(n-1)}),$$

행렬 $B$의 $j$ 열벡터를 
$$
B^j=\left[\begin{array}{cccc} \\
B_{0j} \\
\vdots \\
B_{nj}
\end{array}\right]

라 할 때, 다음이 성립한다.

$$
A^0_i \cdot B^1_j
= A_{i0} \cdot B_{0j} + A_{i2} \cdot B_{2j} + \cdots + A_{i(n-1)} \cdot B_{(n-1)j}
$$

즉, $(A B)_{ij}$는 $A$의 $i$ 행벡터와 $B$의 $j$ 열벡터의 **내적**으로 정의된다.

예를 들어 위의 $2 \times 3$ 행렬과 $3 \times 2$ 행렬의 곱셈을 다시 살펴보자.

$$
\begin{align*}
\begin{bmatrix}
    1&0&2\\-1&3&1
\end{bmatrix}
\cdot 
\begin{bmatrix}
    3&1\\2&1\\1&0
\end{bmatrix}
&=
\begin{bmatrix}
    (1\cdot 3+0\cdot 2+2\cdot 1)&(1\cdot 1+0\cdot 1+2\cdot 0)\\(-1\cdot 3+3\cdot 2+1\cdot 1)&(-1\cdot 1+3\cdot 1+1\cdot 0)
\end{bmatrix}= 
\begin{bmatrix}
    5&1\\4&2
\end{bmatrix}
\end{align*}
$$

위 계산을 벡터 내적으로 표현해보자.
먼저 두 행렬 $A$와 $B$를 지정한다.

$$
A = \begin{bmatrix}
    1&0&2\\-1&3&1
\end{bmatrix} \text{,}
\qquad
B = \begin{bmatrix}
    3&1\\2&1\\1&0
\end{bmatrix}
$$

그러면 

$$(A\cdot B)_{21}= A_2 \cdot B^1=-1\cdot 3+3\cdot 2+1\cdot 1 = 4$$

$$
\begin{align*}
A^0_1 \cdot B^1_1
&= 
\begin{bmatrix}
    -1&3&1
\end{bmatrix}
\cdot
\begin{bmatrix}
    1 & 1 & 0
\end{bmatrix} \\[.5ex]
&=
-1\cdot 1+3\cdot 1+1\cdot 0 \\
&=
2
\end{align*}
$$

## 행렬 연산(합, 곱) 항등원과 역원

- 행렬의 덧셈 연산에 대한 항등원은 영행렬로 $O$으로 나타내자.  
- 행렬 $A$ 합에 대한 역원을 $B$라 하면 
$$
A + B = B + A = O
$$
이다. 
- $B = (-1)A$이며 $-A$로 나타낸다.  

- $n\times n$ 행렬들의 곱셈에 대한 항등원을 $I_n$이다. 즉, 임의의 $n\times n$ 행렬 $A$에 대하여

$$ 
A I_n = I_n A = A
$$
이다. 

- $n$ 차의 정사각행렬 $A$의 곱셈에 대한 역원 $B$는 다음을 만족한다: 
$$
A B=B A=I_{n}
$$

### 정의. [역행렬, 가역/비가역 행렬]


- $n$ 차의 정사각행렬 $A$에 대하여 $A B=I_{n}=BA$을 만족하는 행렬 $B$를 행렬 $A$의 역행렬이라 하며 $A^{-1}$로 표현한다. 즉, $B = A^{-1}$이다.    


- $n$ 차의 정사각행렬 $A$의 곱셈에 대한 역원이 존재하면 $A$ 는 가역(invertible, nonsingular)이라고 한다.  

  
- 이러한 $B$ 가 존재하지 않으면 $A$ 는 비가역 (noninvertible, singular)이라고 한다.

## 전치행렬

행렬의 **전치**란 행과 열을 바꾸는 것으로, 행렬 $A$의 전치는 $A^T$로 나타낸다. 

즉, $A = [A_{ij}]$가 $m \times n$ 행렬이면 $A^T$는 $n \times m$ 행렬이며,
 $A^T$의 $i$행의 $j$열번째 값은 $A$의 $j$행의 $i$열번째 값이다. 
즉,

$$
A ^{T}_{ij} = A_{ji}
$$

예를 들어, $2\times 3$ 행렬의 전치는 $3 \times 2$ 행렬이 되며 다음과 같이 작동한다.

$$
\begin{bmatrix}
    9&8&7\\
    -1&3&4
\end{bmatrix}^{T}
=
\begin{bmatrix}
    9&-1\\
    8&3\\
    7&4
\end{bmatrix}
$$

### 정리. [전치행렬의 성질]

$a$를 스칼라, $A, B$를 크기가 같은 행렬이라 하자. 이때 다음이 성립한다.

* $(A^T)^T = A$
* $(A + B)^T = A^T + B^T$
* $(A - B)^T = A^T - B^T$
* $(a\cdot A)^T = a\cdot A^T$
* $(A B)^T = B^T A^T$

### 정리. [전치행렬의 성질]

$a$를 스칼라, $A, B$를 크기가 같은 행렬이라 하자. 이때 다음이 성립한다.

* $(A^T)^T = A$
* $(A + B)^T = A^T + B^T$
* $(A - B)^T = A^T - B^T$
* $(a\cdot A)^T = a\cdot A^T$
* $(A B)^T = B^T A^T$

## 전치행렬

행렬의 **전치**란 행과 열을 바꾸는 것으로, 행렬 $A$의 전치는 $A^T$로 나타낸다. 

즉, $A = [A_{ij}]$가 $m \times n$ 행렬이면 $A^T$는 $n \times m$ 행렬이며,
 $A^T$의 $i$행의 $j$열번째 값은 $A$의 $j$행의 $i$열번째 값이다. 
즉,

$$
A ^{T}_{ij} = A_{ji}
$$

예를 들어, $2\times 3$ 행렬의 전치는 $3 \times 2$ 행렬이 되며 다음과 같이 작동한다.

$$
\begin{bmatrix}
    9&8&7\\
    -1&3&4
\end{bmatrix}^{T}
=
\begin{bmatrix}
    9&-1\\
    8&3\\
    7&4
\end{bmatrix}
$$

### 정리. [전치행렬의 성질]

$a$를 스칼라, $A, B$를 크기가 같은 행렬이라 하자. 이때 다음이 성립한다.

* $(A^T)^T = A$
* $(A + B)^T = A^T + B^T$
* $(A - B)^T = A^T - B^T$
* $(a\cdot A)^T = a\cdot A^T$
* $(A B)^T = B^T A^T$

## $\blacktriangleright$ Numpy 사용  

- ### 주어진 행렬을 numpy에서의 2차원 array를 사용하여 구현한다.  

다음의 행렬 $X, Y,Z$를 각각  (2, 3) 모양(shape)
그리고  $Z$ (3,2)모양의 2차원 어레이로 구현하여 계산한다.

$$
X =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

$$
Y =
\begin{bmatrix}
9 & 2 & 3 \\
0 & 5 & 3
\end{bmatrix}
$$

$$
Z =
\begin{bmatrix}
1 & -2 \\
7 & 3 \\
4 & 5 
\end{bmatrix}
$$

In [176]:
import numpy as np

In [177]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
Y = np.array([[9, 2., 3.], [0, 5, 3]])
Y

array([[9., 2., 3.],
       [0., 5., 3.]])

In [179]:
Z = np.array([[1, -2], [7, 3], [4, 5]])
Z

array([[ 1, -2],
       [ 7,  3],
       [ 4,  5]])

- ### 행렬 합, 스칼라곱 

In [180]:
X + Y

array([[10.,  4.,  6.],
       [ 4., 10.,  9.]])

In [181]:
2*X

array([[ 2,  4,  6],
       [ 8, 10, 12]])

- ### 행렬 곱셈 

In [182]:
X.dot(Z)

array([[27, 19],
       [63, 37]])

In [183]:
X@Z

array([[27, 19],
       [63, 37]])

`np.dot()` 함수를 이용해도 동일한 결과를 얻는다.

In [184]:
np.dot(X,Z)  

array([[27, 19],
       [63, 37]])

- ### 전치행렬 

전치 행렬은 전치 어레이로 구현된다.

In [185]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [186]:
Z.T

array([[ 1,  7,  4],
       [-2,  3,  5]])

$XZ$ 의 전치 행렬은 $Z$의 전치 행렬과 $X$의 전치 행렬의 곱이다.

In [187]:
((X @ Z).T == Z.T @ X.T).all()

True

In [188]:
(X @ Z).T == Z.T @ X.T

array([[ True,  True],
       [ True,  True]])

- ### 역행렬 

역행렬은 `numpy.linalg` 모듈에 포함된 `inv()` 함수를 이용하여 구한다.

In [189]:
W = np.array([[3,4],[-1, 2]])

In [190]:
np.linalg.inv(W)

array([[ 0.2, -0.4],
       [ 0.1,  0.3]])

In [191]:
from numpy.linalg import inv

In [192]:
inv(W)

array([[ 0.2, -0.4],
       [ 0.1,  0.3]])

# 행렬식과 벡터의 외적

## 행렬식

### 치환(permutation, 순열)  

- 자연수의 집합 $S=\{1,2, \ldots, n\}$ 의 치환(permutation, 순열)이란 $S$ 에서 $S$ 로의 일대일 대응 함수이다.

- 앞으로 치환을 간단히 $\sigma=(\sigma(1) \sigma(2) \cdots \sigma(n))=\left(i_{1} i_{2} \cdots i_{n}\right)$ 로 나타낸다. 

- 치환 $\sigma$ 는 일대일대응이므로 치역 $\left\{i_{1}, i_{2}, \ldots, i_{n}\right\}$ 은 $1,2, \ldots, n$ 의 숫자를 일렬로 배열하는 것에 지나지 않는다.   
따라서 $S=\{1,2, \cdots, n\}$ 의 치환은 모두 $n !$ 개이다. 집합 $S$ 의 모든 치환의 집합을 $S_{n}$ 으로 표시한다. 

### 반전(inversion)

- 치환 $\left(j_{1} j_{2} \cdots j_{n}\right)$ 에서 반전(inversion)이란 큰 자연수가 작은 자연수보다 더 왼쪽에 먼저 나타나는 경우를 말한다. 

- 예를 들어 아래 그림의 치환 $(1423)$ 에서 4 는 2 보다 더 왼쪽에 있 으므로 (4 2)에서 반전이 일어났다. 마찬가지로 (4 3)에서도 반전이 일어났다.  
$$
(1(4)(2) 3)
$$

### 짝수치환(even permutation),/ 홀치환(odd permutation)

- 치환이 가진 반전의 총 개수가 짝수이면 이 치환은 짝수치환(even permutation), 홀수이면 홀치환(odd permutation)이라고 한다.

- $S_{n}$ 의 각 치환을 $+1$ 또는 $-1$ 이라는 수에 대응시키는 부호화 함수(signature function)
- 
$\operatorname{sgn}$ : ${S}_{n} \rightarrow\{+1,-1\}$ 을 다음과 같이 정의한다.

$$
\operatorname{sgn}(\sigma)= \begin{cases}+1 & (\sigma: \text { 짝치환 }) \\ -1 & (\sigma: \text { 홀치환 })\end{cases}
$$

### 정의. [행렬식] 

- 행렬 $A=\left[a_{i j}\right]$ 가 $n$ 차의 정사각행렬일 때, $A$ 의 행렬식을 $\operatorname{det}(A)$ 또는 $|A|$ 로 나타내고 다음 과 같이 정의한다.

$$
\operatorname{det}(A)=\sum_{\sigma \in S_{n}} \operatorname{sgn}(\sigma) a_{1\sigma(1)} a_{2\sigma(2)} \cdots a_{n\sigma(n)}
$$

- 정의에 의하여 1 차 정사각행렬 $A=[a]$ 의 행렬식은 $\operatorname{det}(A)=a$ 이다.  

- 행렬식의 각 항 $\operatorname{sgn}(\sigma) a_{1\sigma(1)} a_{2\sigma(2)} \cdots a_{n\sigma(n)}$ 은 행렬 $A$ 의 행과 열에서 중복됨 없이 하나씩 뽑 아서 곱한 후 대응되는 치환의 부호를 붙인 것이다.
 
예를 들어 $3 \times 3$ 행렬 $A$의 행렬식을 구해보자.

$$ S_3= \{(123), (132), (231), (213), (312), (321)\} $$

이므로 행렬식을 계산하면 모두 6개의 항이 있게 되고 

$$\operatorname{det}(A)= a_{11}(a_{22}a_{33}- a_{23}a_{32}) - a_{12}(a_{21}a_{33}- a_{23}a_{31}) +  a_{13}(a_{21}a_{32}- a_{22}a_{31})$$

이고 이는 다음의 식을 의미한다. 즉,

$$
a_{11}\left|\begin{array}{ll}
a_{22} & a_{23} \\
a_{32} & a_{33}
\end{array}\right|
- a_{12}\left|\begin{array}{ll}
a_{21} & a_{23} \\
a_{31} & a_{33}
\end{array}\right|
+ a_{13}\left|\begin{array}{ll}
a_{21} & a_{22} \\
a_{31} & a_{32}
\end{array}\right|
$$

**[예제]**  다음 행렬 $B$의 행렬식을 구하여라.

$$
B =\left[\begin{array}{ccc}
2 & 1& -1 \\
4 & 1& 2 \\
1 & 5 & -2
\end{array}\right]
$$

**답**
$-33$




### 정리. [행렬식의 성질]  

(1) $A$ 가 가역행렬일 필요충분조건은 $\operatorname{det} A \neq 0$ 이다.  

(2) 두 행렬 $A, B$ 가 $n$ 차의 정사각행렬일 때, $|A B|=|A||B|$ 이 성립한다.  

(3) 행렬 $A$ 가 가역이면 $|A| \neq 0$ 이고, $\left|A^{-1}\right|=\frac{1}{|A|}$ 이 성립한다.



## 외적(outer product, cross product)

두 벡터 $U$ 와 $V$ 의 외적은 기호 $U \times V$ 로 표현하며, 다음과 같이 정의 된다.

### 정의. [외적] 

성분을 사용한 정의

$U=\left(u_{1}, u_{2}, u_{3}\right)$ 과 $V=\left(v_{1}, v_{2}, v_{3}\right)$ 라 할 때 단위벡터들 $i, j, k$ 를 사 용하여, $U \times V$ 는 다음과 같은 $3 \times 3$ 행렬식으로 정의된다.

$$
U \times V=\left|\begin{array}{ccc}
i & j & k \\
u_{1} & u_{2} & u_{3} \\
v_{1} & v_{2} & v_{3}
\end{array}\right|
$$

이 행렬식을 풀어 쓰면 다음과 같다.

$$
\begin{aligned}
U \times V &=\left|\begin{array}{ll}
u_{2} & u_{3} \\
v_{2} & v_{3}
\end{array}\right|i- \left|\begin{array}{ll}
u_{1} & u_{3} \\
v_{1} & v_{3}
\end{array}\right|j+ \left|\begin{array}{ll}
u_{1} & u_{2} \\
v_{1} & v_{2}
\end{array}\right| k \\
&=\left(u_{2} v_{3}-u_{3} v_{2}\right) i-\left(u_{1} v_{3}-u_{3} v_{1}\right) j+\left(u_{1} v_{2}-u_{2} v_{1}\right) k
\end{aligned}
$$

**[예제]** 벡터 $U=(1,2,3), V=(1,3,5)$ 일 때, $U \times V$ 와 $V \times U$ 를 구하여라.

**풀이** 

$$
\begin{aligned}
U \times V &=\left|\begin{array}{ccc}
i & j & k \\
1 & 2 & 3 \\
1 & 3 & 5
\end{array}\right| \\
&=i(2 \cdot 5-3 \cdot 3)-j(1 \cdot 5-1 \cdot 3)+k(1 \cdot 3-1 \cdot 2) \\
&=i-2 j+k=(1,-2,1) 
\end{aligned}
$$


$$
\begin{aligned}
V \times U &=\left|\begin{array}{ccc}
i & j & k \\
1 & 3 & 5 \\
1 & 2 & 3
\end{array}\right| \\
&=i(3 \cdot 3-2 \cdot 5)-j(1 \cdot 3-1 \cdot 5)+k(1 \cdot 2-1 \cdot 3) \\
&=-i+2 j-k=(-1,2,-1)
\end{aligned}
$$

### 정리. [외적의 성질] 

 (1) 벡터 $U$ 에서 $V$ 방향으로 이루는 사잇각을 $\theta$ 라 할 때, 벡터의 외적은

$$
U \times V=(\|U\|\|V\| \sin \theta) E
$$

와 같다. 여기서 $E$ 는 $U$ 와 $V$ 에 의해 만들어지는 평면에 수직한 단위벡터 이다.

(2) 벡터 $\left(u_{2} v_{3}-u_{3} v_{2}\right) i-\left(u_{1} v_{3}-u_{3} v_{1}\right) j+\left(u_{1} v_{2}-u_{2} v_{1}\right) k$ 는 $U$ 와 수직이며 동시에 $V$ 와도 수직이다.

(3) 실제로 $U \times V=(\|U\|\|V\| \sin \theta) E$ 의 방향은 다음과 같이 오른손 나사 방향으로 볼 수 있다.

### 증명  

(1) $U=\left(u_{1}, u_{2}, u_{3}\right), V=\left(v_{1}, v_{2}, v_{3}\right)$ 이라고 하자. $\theta$ 는 $U$ 에서 $V$ 방향으 로 잰 사잇각 이므로 다음의 두 가지를 보이면 충분하다.

$$
\begin{aligned}
\|U \times V\|^2 &=\left\|\left(u_{2} v_{3}-u_{3} v_{2}\right) i-\left(u_{1} v_{3}-u_{3} v_{1}\right) j+\left(u_{1} v_{2}-u_{2} v_{1}\right) k\right\|^2 \\
&=\left(u_{2} v_{3}-u_{3} v_{2}\right)^{2}+\left(u_{1} v_{3}-u_{3} v_{1}\right)^{2}+\left(u_{1} v_{2}-u_{2} v_{1}\right)^{2} \\
&=u_{2}^{2} v_{3}^{2}-2 u_{2} v_{3} u_{3} v_{2}+u_{3}^{2} v_{2}^{2}+u_{1}^{2} v_{3}^{2}-2 u_{1} v_{3} u_{3} v_{1}+u_{3}^{2} v_{1}^{2} \\
&\quad+u_{1}^{2} v_{2}^{2}-2 u_{1} v_{2} u_{2} v_{1}+u_{2}^{2} v_{1}^{2} \\
&=\left(u_{1}^{2}+u_{2}^{2}+u_{3}^{2}\right)\left(v_{1}^{2}+v_{2}^{2}+v_{3}^{2}\right)-\left(u_{1} v_{1}+u_{2} v_{2}+u_{3} v_{3}\right)^{2} \\
&=\|U\|^{2}\|V\|^{2}-|U \cdot V|^{2} \\
&=\|U\|^{2}\|V\|^{2}-(\|U\|\|V\| \cos \theta)^{2} \\
&=\|U\|^{2}\|V\|^{2}\left(1-\cos ^{2} \theta\right) \\
&=(\|U\|\|V\| \sin \theta)^{2}
\end{aligned}
$$

따라서

$$
\left\|\left(u_{2} v_{3}-u_{3} v_{2}\right) i-\left(u_{1} v_{3}-u_{3} v_{1}\right) j+\left(u_{1} v_{2}-u_{2} v_{1}\right) k\right\|=\|U\|\|V\| \sin \theta
$$
이다.

(2) 계산에 의하여 쉽게 증명할 수 있다. 

(3) $\{U, V, U\times V \}$를 순서대로 행벡터로 하는 행렬의 행렬식이 양수임을 보인다. 


![images/fig_outerproduct.png](images/fig_outerproduct.png)
<img src="images/fig_outerproduct.png" width="60%">

## $\blacktriangleright$ Numpy 사용  

- 행렬식

In [193]:
import numpy as np

In [194]:
B = np.array([[2,1,-1],[4,1,2],[1,5,-2]])
B

array([[ 2,  1, -1],
       [ 4,  1,  2],
       [ 1,  5, -2]])

In [195]:
np.linalg.det(B)

-33.0

- 벡터 외적

In [196]:
import numpy as np

In [197]:
v1 = np.array([3,1,4])
v2 = np.array([-2,5,3])

print("v1 = " )
print(v1)
print("v2 =" )
print(v2)

v1 = 
[3 1 4]
v2 =
[-2  5  3]


In [198]:
np.cross(v1,v2)

array([-17, -17,  17])

In [199]:
v3 = np.cross(v1,v2)

type(v3)

numpy.ndarray

In [200]:
v3

array([-17, -17,  17])