In [20]:
import numpy as np

In [21]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
arr[3]

3

In [23]:
arr[4:6]

array([4, 5])

In [24]:
arr[4:6] = 12
arr

array([ 0,  1,  2,  3, 12, 12])

In [25]:
arr_slice = arr[2:3]
arr_slice

array([2])

In [26]:
arr_slice[:] = 64
arr_slice

array([64])

In [27]:
arr

array([ 0,  1, 64,  3, 12, 12])

In [28]:
arr2d = np.array([[1, 2], [4, 5], [7, 8]])
arr2d

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
arr2d[0]

array([1, 2])

In [30]:
arr2d[0][1]

2

In [31]:
arr3d = np.array([[[1, 2], 
                   [4, 5]], 
                  
                  [[7, 8], 
                   [10, 11]]])
arr3d

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [32]:
arr3d.shape

(2, 2, 2)

In [33]:
arr3d[0]

array([[1, 2],
       [4, 5]])